type("Normal").
type("Fighting").
type("Flying").
type("Poison").
type("Ground").
type("Rock").
type("Bug").
type("Ghost").
type("Steel").
type("Fire").
type("Water").
type("Grass").
type("Electric").
type("Psychic").
type("Ice").
type("Dragon").
type("Dark").
type("Fairy").
type("Unknown").
type("Shadow").
